### PR TITLE
Add type compiler.

### PR DESCRIPTION
**Pull request by jmcarp**
Map generic datatypes to bigquery datatypes.

With this patch, I was able to create tables with common types via pybigquery.

### CODE REVIEW

**Comment by tswast** [comment]
Neat!

I know we have a dictionary from BigQuery types to SQLAlchemy types. Would it make sense to invert that dictionary and use it for these methods? I hate to have the same mapping defined in two places, but I guess this is the only place so far where we need to go from SQLAlchemy types to BigQuery types.

**Comment by jmcarp** [comment]
Amended to add a few more common types.

**Comment by jmcarp** [comment]
I was testing with sqlalchemy core, which apparently does support tables without primary keys. For sqlalchemy declarative, tables without primary keys [aren't supported](https://docs.sqlalchemy.org/en/latest/faq/ormconfiguration.html#how-do-i-map-a-table-that-has-no-primary-key), but I added a ddl compiler that skips foreign and primary keys on table creation.

**Comment by mxmzdlv** [comment]
Thanks!

**Pull request merged**
