### PR TITLE
Fetch table and column descriptions

### PR DESCRIPTION
**Pull request by hsheth2**
A fairly simple change to fetch descriptions during reflection. It just follows the directives set up by the docs https://docs.sqlalchemy.org/en/13/core/internals.html#sqlalchemy.engine.default.DefaultDialect.

### CODE REVIEW

**Comment by hsheth2** [comment]
@mxmzdlv - would appreciate if you could take a look at this when you get a chance

**Comment by hsheth2** [comment]
@tswast - as the last person to merge code into this repo, do you know who's the right person to ask in order to get some feedback/guidance on this?

**Comment by alonme** [comment]
@hsheth2 - it sometimes take them some time to get to PRs.
Maybe a good start would be to add some tests for this

**Review by tswast — APPROVED** [review]
I've added tests for the relevant functionality. Looks good to me.

Thanks for the contribution @hsheth2 !

**Comment by hsheth2** [comment]
@tswast thanks for adding the tests and getting this over the finish line :)

**Pull request merged**
