### PR TITLE
Add support for STRUCT and ARRAY types.

### PR DESCRIPTION
**Pull request by tswast**
Also called RECORD and REPEATED fields.

Closes https://github.com/mxmzdlv/pybigquery/issues/4

### CODE REVIEW

**Comment by tswast** [comment]
Note: I created this from the GitHub web UI. Ideally we'd add some tests for these queries to make sure this actually fixes the issue.

**Comment by sumedhsakdeo** [comment]
I check out this PR, build a python whl, and tested it locally against a BQ table with nested fields. And it works!
Thank you so much!

**Comment by tswast** [comment]
I'm adding some tests now. I need to fix one thing for arrays.

**Comment by tswast** [comment]
@sumedhsakdeo I'm glad the fix worked for you. Thanks for trying it out!

I believe this PR is ready for review now. I've added tests and updated the logic to also work for REPEATED / ARRAY types.

**Comment by mxmzdlv** [comment]
This is fantastic. Thank you @tswast!

**Pull request merged**
